In [83]:
import pandas as pd 
import tensorflow
import numpy as np 
import pickle

In [2]:
df=pd.read_csv('Churn_Modelling.csv')

In [3]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [8]:
df.drop(columns=['RowNumber','CustomerId','Surname'],axis=0,inplace=True)

In [9]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X=df.drop('Exited',axis=1)

In [16]:
y=df['Exited']

In [18]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [19]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=10)

In [21]:
X_train.shape

(8000, 10)

In [22]:
X_test.shape

(2000, 10)

In [23]:
y_train.shape

(8000,)

In [24]:
y_test.shape

(2000,)

In [25]:
X_train.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
dtype: int64

In [27]:
X_test.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
dtype: int64

In [35]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [29]:
lb=LabelEncoder()

In [30]:
X_train['Gender']=lb.fit_transform(X_train['Gender'])

In [31]:
X_train

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
7496,824,Germany,1,49,8,133231.48,1,1,1,67885.37
7694,676,Spain,0,64,4,116954.32,1,1,1,91149.48
9248,629,Spain,1,34,6,0.00,2,1,0,190347.72
2470,689,Spain,0,31,3,139799.63,1,0,1,120663.57
4392,787,France,1,51,0,58137.08,1,0,1,142538.31
...,...,...,...,...,...,...,...,...,...,...
9372,677,France,1,30,1,78133.15,1,0,1,174225.88
7291,599,Spain,1,33,4,51690.89,1,1,0,111622.76
1344,460,Germany,0,40,6,119507.58,2,1,0,91560.63
7293,709,France,0,34,2,111669.68,1,1,0,57029.66
1289,672,Germany,1,40,10,102980.44,1,1,0,1285.81

In [33]:
X_test['Gender']=lb.transform(X_test['Gender'])

In [34]:
X_test

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
937,850,Germany,0,44,5,128605.32,1,0,1,171096.20
9355,739,Spain,0,40,8,0.00,1,1,0,167030.51
2293,689,Spain,0,45,0,57784.22,1,1,0,197804.00
192,479,France,1,40,1,0.00,2,0,0,114996.43
8675,714,France,1,54,7,126113.28,1,1,0,112777.38
...,...,...,...,...,...,...,...,...,...,...
5624,617,Spain,0,45,1,0.00,1,1,0,143298.06
6005,636,France,0,24,9,0.00,2,0,1,38830.72
987,569,Spain,1,34,0,151839.26,1,1,0,102299.81
6152,508,France,0,64,2,0.00,1,1,1,6076.62
2092,655,Spain,1,38,3,250898.09,3,0,1,81054.00

In [ ]:

encoder = OneHotEncoder()

geo_encoded = encoder.fit_transform(X_train[['Geography']])

geo_df = pd.DataFrame(geo_encoded.toarray(), columns=encoder.get_feature_names_out())


X_train = X_train.reset_index(drop=True)
geo_df = geo_df.reset_index(drop=True)


X_train = pd.concat([X_train.drop('Geography', axis=1), geo_df], axis=1)

In [77]:
X_train

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,824,1,49,8,133231.48,1,1,1,67885.37,0.0,1.0,0.0
1,676,0,64,4,116954.32,1,1,1,91149.48,0.0,0.0,1.0
2,629,1,34,6,0.00,2,1,0,190347.72,0.0,0.0,1.0
3,689,0,31,3,139799.63,1,0,1,120663.57,0.0,0.0,1.0
4,787,1,51,0,58137.08,1,0,1,142538.31,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7995,677,1,30,1,78133.15,1,0,1,174225.88,1.0,0.0,0.0
7996,599,1,33,4,51690.89,1,1,0,111622.76,0.0,0.0,1.0
7997,460,0,40,6,119507.58,2,1,0,91560.63,0.0,1.0,0.0
7998,709,0,34,2,111669.68,1,1,0,57029.66,1.0,0.0,0.0
7999,672,1,40,10,102980.44,1,1,0,1285.81,0.0,1.0,0.0

In [78]:
geo_encoded = encoder.transform(X_test[['Geography']])

geo_df = pd.DataFrame(geo_encoded.toarray(), columns=encoder.get_feature_names_out())


X_test = X_test.reset_index(drop=True)
geo_df = geo_df.reset_index(drop=True)


X_test = pd.concat([X_test.drop('Geography', axis=1), geo_df], axis=1)

In [79]:
X_test

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,850,0,44,5,128605.32,1,0,1,171096.20,0.0,1.0,0.0
1,739,0,40,8,0.00,1,1,0,167030.51,0.0,0.0,1.0
2,689,0,45,0,57784.22,1,1,0,197804.00,0.0,0.0,1.0
3,479,1,40,1,0.00,2,0,0,114996.43,1.0,0.0,0.0
4,714,1,54,7,126113.28,1,1,0,112777.38,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,617,0,45,1,0.00,1,1,0,143298.06,0.0,0.0,1.0
1996,636,0,24,9,0.00,2,0,1,38830.72,1.0,0.0,0.0
1997,569,1,34,0,151839.26,1,1,0,102299.81,0.0,0.0,1.0
1998,508,0,64,2,0.00,1,1,1,6076.62,1.0,0.0,0.0
1999,655,1,38,3,250898.09,3,0,1,81054.00,0.0,0.0,1.0

In [82]:
X_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CreditScore        8000 non-null   int64
 1   Gender             8000 non-null   int64
 2   Age                8000 non-null   int64
 3   Tenure             8000 non-null   int64
 4   Balance            8000 non-null   float64
 5   NumOfProducts      8000 non-null   int64
 6   HasCrCard          8000 non-null   int64
 7   IsActiveMember     8000 non-null   int64
 8   EstimatedSalary    8000 non-null   float64
 9   Geography_France   8000 non-null   float64
 10  Geography_Germany  8000 non-null   float64
 11  Geography_Spain    8000 non-null   float64
dtypes: float64(5), int64(7)
memory usage: 750.1 KB

In [81]:
X_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CreditScore        2000 non-null   int64
 1   Gender             2000 non-null   int64
 2   Age                2000 non-null   int64
 3   Tenure             2000 non-null   int64
 4   Balance            2000 non-null   float64
 5   NumOfProducts      2000 non-null   int64
 6   HasCrCard          2000 non-null   int64
 7   IsActiveMember     2000 non-null   int64
 8   EstimatedSalary    2000 non-null   float64
 9   Geography_France   2000 non-null   float64
 10  Geography_Germany  2000 non-null   float64
 11  Geography_Spain    2000 non-null   float64
dtypes: float64(5), int64(7)
memory usage: 187.6 KB

In [85]:
with open('OneHotEncoder.pkl','wb') as file :
    pickle.dump(encoder,file)
with open('labelencoder.pkl','wb') as file :
    pickle.dump(lb,file)

## Model training with the help of ann

In [86]:
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
from sklearn.preprocessing import StandardScaler

In [87]:
scalar=StandardScaler()

In [88]:
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [92]:
X_train.shape[1]

12

In [90]:
model=Sequential([
    Dense(32,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),

    Dense(1,activation='sigmoid')
]
)

e:\ann\venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [91]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,505 (5.88 KB)

 Trainable params: 1,505 (5.88 KB)

 Non-trainable params: 0 (0.00 B)

In [95]:

opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [96]:
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [97]:
import datetime

In [100]:

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [102]:
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [103]:
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8357 - loss: 0.3898 - val_accuracy: 0.8470 - val_loss: 0.3672
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8565 - loss: 0.3530 - val_accuracy: 0.8425 - val_loss: 0.3770
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8581 - loss: 0.3447 - val_accuracy: 0.8425 - val_loss: 0.3685
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8612 - loss: 0.3407 - val_accuracy: 0.8420 - val_loss: 0.3657
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8622 - loss: 0.3359 - val_accuracy: 0.8515 - val_loss: 0.3569
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8639 - loss: 0.3337 - val_accuracy: 0.8500 - val_loss: 0.3668
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8611 - loss: 0.3330 - val_accuracy: 0.8515 - val_loss: 0.3620
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8649 - loss: 0.3302 - val_accuracy: 0.8470 - val_loss: 0.3707
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8640 - loss: 0.3310 - val_accuracy: 0.8480 - val_loss: 0.3596
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8671 - loss: 0.3255 - val_accuracy: 0.8430 - val_loss: 0.3720

In [104]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [105]:
with open('scalar.pkl','wb')as file :
    pickle.dump(scalar,file)

In [110]:
## Load Tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [113]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 7256), started 0:02:07 ago. (Use '!kill 7256' to kill it.)